server:
  port: 9999

zuul:
  routes:
    api:
      path: /api/**
      url: http://localhost:8080/api
    auth:
      path: /auth/**
      url: http://localhost:8080/auth
    api-docs:
      path: /api-docs/**
      url: http://localhost:8080